databases:
  - name: soundscape_database
    databaseName: soundscape_database_qmu3
    user: soundscape_database_qmu3_user

services:
  - type: web
    name: railsapp-soundscape
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:  soundscape_database_qmu3
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false