databases:
  - name: soundscape
    databaseName: soundscape
    user: soundscape_user

services:
  - type: web
    name: SoundScape
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: soundscape
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false