databases:
  - name: Soundscape_database
    databaseName: soundscape_database
    user: soundscape_database_user

services:
  - type: web
    name: soundscape-development
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: soundscape_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false