databases:
  - name: soundscape_development
    databaseName: soundscape_development
    user: soundscape_development

services:
  - type: web
    name: soundscape-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: soundscape_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false