databases:
  - name: db-soundscape
    databaseName: db_soundscape
    user: db_soundscape_user

services:
  - type: web
    name: server-soundscape
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db_soundscape
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false